## Numpy를 사용하는 이유

- 성능: 파이썬 리스트보다 빠름
- 메모리 사이즈: 파이썬 리스트보다 적은 메모리 사용
- 빌트인 함수: 선형대수, 통계관련 여러 함수 내장

---
## ndarray

연속된 메모리 Vectorization 사용

In [1]:
import numpy as np
import matplotlib.pyplot as plt

### ndarray 생성 방법

In [11]:
print("=== np.array ===")
print("list를 ndarray로:\n",
      np.array([1,2,3]))

=== np.array ===
list를 ndarray로:
 [1 2 3]


In [12]:
print("\n=== np.arange ===")
print("길이 지정:\n",
      np.arange(10))
print("시작과 끝 지정:\n",
      np.arange(1,10))
print("시작과 끝, 간격 지정:\n",
      np.arange(1,10,2))


=== np.arange ===
길이 지정:
 [0 1 2 3 4 5 6 7 8 9]
시작과 끝 지정:
 [1 2 3 4 5 6 7 8 9]
시작과 끝, 간격 지정:
 [1 3 5 7 9]


In [13]:
print("\n=== np.ones, np.zeros ===")
print("행렬의 형태를 튜플로 지정:\n",
      np.ones((3,4)))
print("행렬의 형태를 튜플로 지정:\n",
      np.zeros((3,4,2)))


=== np.ones, np.zeros ===
행렬의 형태 지정:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
행렬의 형태 지정:
 [[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


In [16]:
print("\n=== np.empty, np.full ===")
print("행렬의 형태를 튜플로 지정(초기화가 되지 않음):\n",
      np.empty((3,4)))
print("행렬의 형태를 튜플로 지정하고 값도 넘겨줌:\n",
      np.full((3,4),7))


=== np.empty, np.full ===
행렬의 형태를 튜플로 지정(초기화가 되지 않음):
 [[3.5e-323 3.5e-323 3.5e-323 3.5e-323]
 [3.5e-323 3.5e-323 3.5e-323 3.5e-323]
 [3.5e-323 3.5e-323 3.5e-323 3.5e-323]]
행렬의 형태를 튜플로 지정하고 값도 넘겨줌:
 [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [17]:
print("\n=== np.eye ===")
print("단위행렬 크기 지정:\n",
      np.eye(3))


=== np.eye ===
단위행렬 크기 지정:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
print("\n=== np.linspace ===")
print("시작, 끝, 수 지정:\n",
      np.linspace(1,10,5))


=== np.linspace ===
시작, 끝, 수 지정:
 [ 1.    3.25  5.5   7.75 10.  ]


### reshpe

In [21]:
x = np.arange(1,16)
print(x)

print(x.reshape(3,5))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


### random

In [23]:
# rand
# 0과 1 사이의 분포로 랜덤한 ndarray생성
np.random.rand(2,3)

array([[0.50312721, 0.27978402, 0.31484109],
       [0.26736883, 0.15193282, 0.56963652]])

In [24]:
# randn
# 정규분포로 랜덤한 ndarray생성
np.random.randn(2,3)

array([[ 1.00800868,  0.82693389,  1.05641879],
       [ 1.25218608,  0.15248729, -0.84137654]])

In [26]:
# randint
# 특정 정수 사이에서 랜덤한 ndarray생성
np.random.randint(1,100, size=(3,5))

array([[83, 83, 27, 62, 19],
       [25, 82, 49, 86, 30],
       [28, 67, 90,  2, 21]])

### seed

In [47]:
# 랜덤한 값을 동일하게 다시 생성하고자 할 때 사용
# seed를 지정한 뒤 random을 호출하는 횟수에따른 값이 항상 같다.
# 첫번째 호출한 값이 다시 seed를 지정하고 첫번째 호출한 값과 같다.
np.random.seed(23)
print(np.random.randn(3,4))
print(np.random.randn(3,4))
print(np.random.randn(3,4))

[[ 0.66698806  0.02581308 -0.77761941  0.94863382]
 [ 0.70167179 -1.05108156 -0.36754812 -1.13745969]
 [-1.32214752  1.77225828 -0.34745899  0.67014016]]
[[ 0.32227152  0.06034293 -1.04345    -1.00994188]
 [ 0.44173637  1.12887685 -1.83806777 -0.93876863]
 [-0.20184052  1.04537128  0.53816197  0.81211867]]
[[ 0.2411063  -0.95250953 -0.13626676  1.26724821]
 [ 0.17363364 -1.22325477  1.41531998  0.45771098]
 [ 0.72887584  1.96843473 -0.54778801 -0.67941827]]


### choice
  
주어진 1차원 ndarray로 부터 랜덤으로 샘플링  
정수가 주어진 경우, np.arange(해당숫자)로 간주

In [50]:
np.random.choice(100, size=(3,4))

array([[26, 37, 41, 56],
       [39, 81, 32, 53],
       [35, 23, 29, 42]])

In [53]:
x = np.arange(100)
print(np.random.choice(x, size=(5,5), replace=False))
print(np.random.choice(x, size=(5,5), replace=True)) # 중복 허용

[[14 12 92 46 94]
 [73 37 19 59 75]
 [30 49 50 13 33]
 [26 47 77 69 55]
 [18 74 27 80 40]]
[[54 77 18 98 56]
 [ 3 35 21 76 57]
 [86 81  0 68 84]
 [21 52 72 93 21]
 [96 60 67 99 60]]


### 확률분포에 따른 ndarray 생성

In [55]:
np.random.uniform(1.0,3.0, size=(4,5))

array([[2.34075612, 2.53384477, 1.99015233, 1.59431279, 1.74101396],
       [2.02903154, 2.81253543, 2.57165079, 2.52918349, 2.64235248],
       [2.43677013, 2.4225355 , 1.81897025, 2.38485115, 1.88328477],
       [2.03332074, 1.9407021 , 1.20625581, 1.58196777, 2.88336093]])

In [56]:
np.random.normal(1.0,3.0, size=(4,5))

array([[-0.62997503, -2.06908821,  5.14505019,  4.19474525,  2.59343559],
       [-2.85545633,  2.6414019 , -0.57733821,  0.32143066,  0.76730818],
       [ 2.3851643 ,  1.27070537,  4.71279161,  0.70400791, -0.36009446],
       [-0.15396785,  2.13004936,  0.97399558, -5.38555523, -1.96210619]])

---
## 인덱싱

In [60]:
# 1차원
x = np.arange(10)
x[0], x[-1], x[3]

(0, 9, 3)

In [68]:
# 2차원 행렬
x = np.random.rand(3,5)
x[0], x[0][2], x[0,2]

(array([0.44994162, 0.89777983, 0.76733343, 0.22698015, 0.93346505]),
 0.7673334343954081,
 0.7673334343954081)

In [67]:
# 3차원 텐서
x = np.random.rand(3,5,4)
x[0], x[0][2], x[0][2][1], x[0,2,1]

(array([[0.95813877, 0.46899631, 0.29207164, 0.65747584],
        [0.2543317 , 0.43629222, 0.75841915, 0.02109411],
        [0.49139727, 0.24160086, 0.52592374, 0.11774792],
        [0.30032559, 0.4390664 , 0.89834013, 0.68692772],
        [0.08359782, 0.37846228, 0.02184493, 0.13135577]]),
 array([0.49139727, 0.24160086, 0.52592374, 0.11774792]),
 0.24160085594403857,
 0.24160085594403857)

---
## 슬라이싱

In [74]:
# 3차원 텐서
x = np.random.rand(3,5,4)
x[0:2], x[0:2,2:,0]

(array([[[0.5997119 , 0.28680602, 0.9901154 , 0.26623961],
         [0.22150764, 0.01788535, 0.38731206, 0.58561483],
         [0.22824516, 0.68455911, 0.60090171, 0.22683283],
         [0.18081258, 0.31539124, 0.20601117, 0.05714546],
         [0.99645226, 0.11711015, 0.5854916 , 0.29607374]],
 
        [[0.62040231, 0.79112253, 0.24018061, 0.47650265],
         [0.91082282, 0.86307209, 0.69608619, 0.7690367 ],
         [0.5443267 , 0.14536227, 0.50633252, 0.05629997],
         [0.48611071, 0.98905417, 0.12229068, 0.99888546],
         [0.05473302, 0.60545594, 0.69168455, 0.6440244 ]]]),
 array([[0.22824516, 0.18081258, 0.99645226],
        [0.5443267 , 0.48611071, 0.05473302]]))

---
## 형태 바꾸기

In [80]:
# ravel
# 다차원을 1차원으로 변경
# 복사하지 않고 값을 활용

x = np.random.rand(2,3)
print(x)
print(x.ravel())
print(np.ravel(x))

print(np.ravel(x, order='C'))
print(np.ravel(x, order='F'))

[[0.52341593 0.36129557 0.98758512]
 [0.79664805 0.38669966 0.15640113]]
[0.52341593 0.36129557 0.98758512 0.79664805 0.38669966 0.15640113]
[0.52341593 0.36129557 0.98758512 0.79664805 0.38669966 0.15640113]
[0.52341593 0.36129557 0.98758512 0.79664805 0.38669966 0.15640113]
[0.52341593 0.79664805 0.36129557 0.38669966 0.98758512 0.15640113]


In [82]:
# flatten
# 다차원을 1차원으로 변경
# 복사본을 활용

x = np.random.rand(2,3)
print(x)
print(x.flatten())
print(x.flatten(order='F'))
# print(np.flatten(x)) 이건 안됨

[[0.40238334 0.47772206 0.04101788]
 [0.9411618  0.20869912 0.27567105]]
[0.40238334 0.47772206 0.04101788 0.9411618  0.20869912 0.27567105]
[0.40238334 0.9411618  0.47772206 0.20869912 0.04101788 0.27567105]


In [88]:
# reshape

x = np.random.rand(4,5)
print(x.shape)
print(x.ndim)

print("=== reshape ===")

x = x.reshape(2,10)
print(x.shape)
print(x.ndim)

print("=== reshape ===")

x = x.reshape(2,-1,2) # 다른 값들을 알면 하나는 -1을 줘도 됨
print(x.shape)
print(x.ndim)

(4, 5)
2
=== reshape ===
(2, 10)
2
=== reshape ===
(2, 5, 2)
3
